db:
    type: mariadb:10.4
    disk: 2048

cache:
    type: redis:6.2

magento_search:
  type: elasticsearch:7.7
  disk: 256
  configuration:
    plugins:
      - analysis-icu
      - analysis-phonetic
